name: umu-run
base: core24
version: 1.4.0
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
summary: Unified launcher for Windows games on Linux
description: |
  This is a unified launcher for Windows games on Linux.
  It is essentially a copy of the Steam Runtime Tools and Steam Linux Runtime that Valve uses for Proton, with some modifications made so that it can be used outside of Steam.
grade: stable
confinement: strict
compression: lzo

apps:
  umu-run:
    command-chain: [define-variables]
    command: usr/bin/umu-run
    desktop: umu-run.desktop
    common-id: org.openwinecomponents.umu.umu-launcher
    extensions: [gnome]
    plugs:
      - audio-playback
      - network
      - network-bind
      - screen-inhibit-control
      - home
      - removable-media
      - mount-observe
      - joystick
      - bluez
      - udisks2
  dot-desktop-creator:
    command: umu-ddc
    desktop: umu-ddc.desktop
    extensions: [gnome]
    plugs:
      - home
      - removable-media
      - mount-observe

plugs:
  shared-memory:
    private: true

parts:
  umu-run-app:
    plugin: dump
    source:
      - on amd64: https://github.com/Open-Wine-Components/umu-launcher/releases/download/$SNAPCRAFT_PROJECT_VERSION/python3-umu-launcher_$SNAPCRAFT_PROJECT_VERSION-1_amd64_ubuntu-noble.deb
      - on arm64: https://github.com/Open-Wine-Components/umu-launcher/releases/download/$SNAPCRAFT_PROJECT_VERSION/python3-umu-launcher_$SNAPCRAFT_PROJECT_VERSION-1_arm64_ubuntu-noble.deb

  dependencies:
    after: [umu-run-app]
    plugin: nil
    stage-packages: [python3-xlib]
    prime: [usr/lib/python3/dist-packages]

  icoutils:
    after: [dependencies]
    plugin: nil
    stage-packages: [icoutils]

  other-files:
    after: [icoutils]
    plugin: dump
    source: ./other-files
