#!/bin/bash

unset PYTHONPATH

export PYTHONPATH="$SNAP/usr/lib/python3/dist-packages:$SNAP/gnome-platform/usr/lib/python3/dist-packages"

if snapctl is-connected home; then
    export HOME="$SNAP_REAL_HOME"
    export UMU_FOLDERS_PATH="$SNAP_REAL_HOME/App/UMU"
else
    export HOME="$SNAP_USER_COMMON"
    export UMU_FOLDERS_PATH="$SNAP_USER_COMMON/App/UMU"
fi

exec "$@"
